refactor: code improvements
vitorlops/Palavreco pull request #19
Opened 2022-09-06 19:15 UTC by vvito7

Here is a list of improvements that I'm doing in this PR:

- Make `utils` export/import easier (created `index.ts` that export all functions from this folder)
- Move `messages.json` `assets.json` `inter.ttf` to another folder (I don't know a good name) to make the above possible
- Better naming for almost everything
- Remove `utils/plataform.ts` since we don't use it anymore

> **Note**
> This PR is still a WIP, but there is no problem in being reviwed

2022-09-10 03:01 UTC, uKaigo requested changes
Hey! Just some changes!

Btw, should probably rename `dunno` to `assets` or something in that nature.

2022-09-10 03:01 UTC, bpleonardo commented on package.json
> +    "prettier": "prettier src --write"
Maybe rename this script to `format`?

2022-09-10 03:01 UTC, bpleonardo commented on src/bot.ts
> +			}
```suggestion
			}
			command.execute(i);
```
Since you're calling it in both true and false, can remove it from the blocks.

2022-09-10 03:01 UTC, bpleonardo commented on src/database.ts
> +import { User, Word } from './interfaces/database';
```suggestion
import { User, Word } from './interfaces/Database';
```

This was causing some of the errors.

2022-09-10 03:01 UTC, bpleonardo commented on src/interfaces/index.ts
> +export * from './database';
```suggestion
export * from './Command';
export * from './Database';
```

2022-09-10 03:01 UTC, bpleonardo commented on src/utils/image.ts
> -const numberPixels = {
Probably better to describe these two too (numberPixels and namePixels). I could only understand it by looking at the rank card (probably my fault tho)

2022-09-10 03:01 UTC, bpleonardo commented on src/commands/rank.ts
>  		const reference: Record<string, number> = {
Since we're here. Would be nice to add a comment describing what this `reference` is. Or change the name.

By looking at it I think it's the multipliers for each _thing_ (don't know how to name it).

2022-09-10 03:01 UTC, bpleonardo commented on src/utils/index.ts
> +export * from './bisect';
Does this actually work? (Cam Casey moment)

Because these files only export defaults, so you can't really `import *` from them. I mean, the ones that export named functions work ofc, but `bisect` for example doesn't.

2022-09-10 19:12 UTC, vvito7 commented on src/database.ts
> +import { User, Word } from './interfaces/database';
This actually isn't needed anymore, since I created a `index.ts` file in this folder too. But I will update!

2022-09-10 19:18 UTC, vvito7 commented on src/interfaces/index.ts
> +export * from './database';
Weird... I remember renaming those files, the code is actually correct, I will update the names.

2022-09-10 19:21 UTC, vvito7 commented on src/utils/image.ts
> -const numberPixels = {
Yeah, there will be a lot of this in this PR still, so I will be describing this too! thanks

2022-09-10 19:21 UTC, vvito7 commented on src/commands/rank.ts
>  		const reference: Record<string, number> = {
`multipliers` is a good name :D

2022-09-18 19:33 UTC, uKaigo approved these changes

2022-09-30 13:49 UTC, merged