feat(adivinhar): save user progress & check if already playing
vitorlops/Palavreco pull request #4
Opened 2022-03-01 20:20 UTC by vitorlops

#### This PR:
- Saves the user progress, i.e. it will still show the words that the user already submitted (this is made by cancelling the game and using the `/adivinhar` command again);
- Check if the user is in an active game, if not it will show an error.

```mermaid
  graph TD;
A[Interaction]-->B{Is in activeGames?};
B -- Yes --> C[Reply with an error];
B -- No --> D[Send the gameMessage and push user ID to activeGames];
D --> E{Is in usersTries?};
E -- Yes --> F[Modify the i, so the for loop will start after];
E -- No --> G[Push playingUser to userTries];
```

2022-03-01 21:16 UTC, uKaigo reviewed
The overall code is fine. Just a few complaints.

2022-03-01 21:16 UTC, bpleonardo commented on src/commands/adivinhar.js
> +const activeGames = [];
In my opinion these would be better as objects.

We're going to be hitting these arrays whenever someone starts a game, so it's nice to have an O(1) lookup.

Though, you know, we're using JS so speed isn't a big concern lol

2022-03-01 21:16 UTC, bpleonardo commented on src/commands/adivinhar.js
> +			const userTries = usersTries.find(user => user.id === interaction.user.id).attempts;
`userTries.find` is run for the second time here. We could move it to a const right before the if.

2022-03-01 21:16 UTC, uKaigo commented on src/commands/adivinhar.js
> +				if (userTries[i] === undefined) {
```suggestion
				if (!userTries[i]) {
``` 

Just a suggestion, there's no problem with the current code. Although there's an [eslint rule](https://eslint.org/docs/rules/no-undefined#no-undefined) against this (which is disabled).

2022-03-01 23:02 UTC, uKaigo requested changes

2022-03-01 23:02 UTC, bpleonardo commented on src/commands/adivinhar.js
> +		activeGames = {};
```suggestion
		for (const obj of [userTries, activeGames]) {
			for (const key in obj) {
				delete obj[key];
			};
		};
```

Only caught this now. The current code will throw a TypeError, since both objects are constants.

Another solution to this is define them with `let`.

2022-03-01 23:02 UTC, bpleonardo commented on src/commands/adivinhar.js
> +			activeGames[interaction.user.id] = null;
```suggestion
			delete activeGames[interaction.user.id];
```
While this works, using `delete` is the correct way to do it, and the equivalent of `splice`.

2022-03-01 23:02 UTC, uKaigo commented on src/commands/adivinhar.js
> +				usersTries[interaction.user.id] = null;
```suggestion
				delete usersTries[interaction.user.id];
```

2022-03-01 23:02 UTC, uKaigo commented on src/commands/adivinhar.js
> +					activeGames[interaction.user.id] = null;
```suggestion
					delete activeGames[interaction.user.id];
```

2022-03-01 23:04 UTC, uKaigo commented on src/commands/adivinhar.js
> +		activeGames = {};
Looks like you fixed it while I was reviewing. So just mark it as outdated.

2022-03-01 23:08 UTC, uKaigo commented on src/commands/adivinhar.js
> +		activeGames = {};
Looks like you fixed it while I was reviewing. So just mark it as outdated :)

2022-03-02 14:30 UTC, uKaigo approved these changes

2022-03-02 15:43 UTC, merged